// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:iceberg_app/src/features/auth/domain/staff_member.dart';
import 'package:iceberg_app/src/features/orders/domain/order.dart';
import 'package:iceberg_app/src/features/products/domain/product.dart';
import 'package:iceberg_app/src/features/reports/domain/shift_report.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(OrderAdapter());
    registerAdapter(OrderItemAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductCategoryAdapter());
    registerAdapter(ShiftReportAdapter());
    registerAdapter(StaffMemberAdapter());
    registerAdapter(StaffRoleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(OrderAdapter());
    registerAdapter(OrderItemAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductCategoryAdapter());
    registerAdapter(ShiftReportAdapter());
    registerAdapter(StaffMemberAdapter());
    registerAdapter(StaffRoleAdapter());
  }
}
